### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by abridgland** [atfrank/PCASA#1]
Hi, it would be great to have some clarification about which license applies to which parts of this repo. At the moment it seems like there's both a LICENSE and COPYING file (the former with an MIT license and the latter with a GPLv3). Since the GPL license is more restrictive I take it that this overrides the MIT license? Thanks!

**Comment by atfrank** [comment]
I've removed the COPYING file with the GPLv3. As such, the MIT license file applies to this repo. Thanks for asking for clarification.
